// ...existing code...
<div
  // ...existing code...
  // Remove or correct the invalid `div` attribute
  // div={true} // Incorrect
  // Correct usage:
  // data-div={true} or remove it entirely
>
// ...existing code...
</div>
// ...existing code...
